#!/bin/sh
fil="$(cat -b $HOME/.bokredoc)"

#Edit colors here, ob is the background color of of the bookmarks title 
reset='\033[0m'
grey='\033[47m'
black='\033[30m'
bold='\033[1m'
ob='\033[43m'

a="${reset}${grey}${bold}${black}"
b="${reset}${ob}${bold}${black}"

echo -e "${b}         ##BOOKMARKS##       ${reset}"
echo -e "${a} ${fil}"${reset}
read -n 1 -s -r -p " Press any key to close"
