#!/bin/sh
fil="$(cat -b $HOME/.bokredoc)"

reset='\033[0m'
grey='\033[47m'
black='\033[30m'
bold='\033[1m'
ob='\033[43m'
gf='\033[30m'

a="${reset}${grey}${bold}${black}"
b="${reset}${ob}${bold}${gf}"

echo -e "${b}         ##BOOKMARKS##       ${reset}"
echo -e "${a} ${fil}"${reset}
read -n 1 -s -r 
