#!/bin/sh
htt="https"
bm="$(xclip -o -primary)"
fil="$HOME/.bokredoc"

if grep -lq "$bm" ~/.bokredoc; then
  notify-send -u critical "Jacob von Rammingen" "Bookmark already added :O"
else
	echo "§ $bm" >> "$fil"
	sort -b "$fil" -o "$fil"
	notify-send "Jacob von Rammingen" "$bm added to bookmarks."
fi
